---
name: Release Node.js SDK
run-name: Release Node.js SDK

on:
    push:
        tags:
            - "*.*.*" # version, e.g. 1.0.0

jobs:
    npm:
        name: Publish NPM
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@08c6903 # v5

            - name: Setup Node
              uses: actions/setup-node@2028fbc # v6
              with:
                  node-version: 22
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Set NPM version
              run: npm version ${{ github.ref_name }} --allow-same-version --no-git-tag-version

            - name: Build SDK
              run: npm run build

            - name: Setup NPM
              run: |
                  echo 'registry="https://registry.npmjs.org/"' > ./.npmrc
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ./.npmrc

                  echo 'registry="https://registry.npmjs.org/"' > ~/.npmrc
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Pack NPM
              run: npm pack

            - name: Publish NPM
              run: npm publish --tarball=./infisical-sdk-${{github.ref_name}} --access public --registry=https://registry.npmjs.org/
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
